// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Ripple: typeof import('@varlet/ui')['_RippleComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
  }
}

export {}
